services:
  backend:
    build:
      context: ./django-backend
    container_name: django_backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./django-backend/db.sqlite3:/app/db.sqlite3
    expose:
      - 8000
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn backtester.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build:
      context: ./django-front
    container_name: vite_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
